// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE4Av2YhkegZI2FglGqB77FW50aD28HVs',
    appId: '1:937523789393:web:75b0bd064f4f111e414270',
    messagingSenderId: '937523789393',
    projectId: 'smartstock-bae61',
    authDomain: 'smartstock-bae61.firebaseapp.com',
    storageBucket: 'smartstock-bae61.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIPgOEUtAaJA_VcmEwVlr1Gj-mQOsQPkQ',
    appId: '1:937523789393:android:d14489852fc17924414270',
    messagingSenderId: '937523789393',
    projectId: 'smartstock-bae61',
    storageBucket: 'smartstock-bae61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU0SHm36omUC85L6b03C8fI79e4X7vOzQ',
    appId: '1:937523789393:ios:6082925d563d5c03414270',
    messagingSenderId: '937523789393',
    projectId: 'smartstock-bae61',
    storageBucket: 'smartstock-bae61.firebasestorage.app',
    iosBundleId: 'com.example.stockManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU0SHm36omUC85L6b03C8fI79e4X7vOzQ',
    appId: '1:937523789393:ios:6082925d563d5c03414270',
    messagingSenderId: '937523789393',
    projectId: 'smartstock-bae61',
    storageBucket: 'smartstock-bae61.firebasestorage.app',
    iosBundleId: 'com.example.stockManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE4Av2YhkegZI2FglGqB77FW50aD28HVs',
    appId: '1:937523789393:web:d2b4a76d8441bfde414270',
    messagingSenderId: '937523789393',
    projectId: 'smartstock-bae61',
    authDomain: 'smartstock-bae61.firebaseapp.com',
    storageBucket: 'smartstock-bae61.firebasestorage.app',
  );
}
